language: node_js

node_js:
  - 12

services:
  - docker

before_install:
  - docker-compose -f docker-compose.dev.yml up
  - docker-compose -f docker-compose.yml up

cache:
  directories:
    - node_modules

script:
  - npm start --silent &
  - npm test
  - npm run build
  - npm run cypress

deploy:
  provider: script
  script: bash scripts/gh-deploy.sh
  keep_history: true
  on:
    branch: gh-pages
