language: node_js

node_js:
  - 12

services:
  - docker

branches:
  only:
    - master

before_install:
  - docker-compose -f docker-compose.dev.yml up --detach --remove-orphans

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: build
      script: npm run build
    - stage: test
      script: npm test
    - stage: cypress
      script: npm run cypress
    - stage: deploy
      script: skip
      deploy:
        provider: script
        script: bash scripts/gh-deploy.sh
        keep_history: true
        on:
          branch: master
