language: node_js

node_js:
  - 12

services:
  - docker

branches:
  only:
    - master

before_install:
  - docker-compose -f docker-compose.dev.yml up --detach --remove-orphans

cache:
  directories:
    - node_modules

script:
  - npm run build
  - npm run cypress
  - npm test

deploy:
  - provider: script
    script: bash scripts/gh-deploy.sh
    keep_history: true
    on:
      branch: master
