language: node_js

node_js:
  - 12

services:
  - docker

branches:
  only:
    - master

before_install:
  - docker-compose -f docker-compose.dev.yml up --detach --remove-orphans

cache:
  directories:
    - node_modules

before_script:
  - npm install -g gh-pages

script:
  - npm run build
  - npm run cypress
  - npm test

deploy:
  - provider: script
    script: npm run deploy
    keep_history: true
    on:
      branch: master
