/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AllowedAction { 
    /**
     * It determines if deleting product is allowed
     */
    _delete: boolean;
    /**
     * It determines if editing product is allowed
     */
    edit: boolean;
    /**
     * It determines if moving product to wishlist is allowed
     */
    moveToWishlist: boolean;
}
