/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PaymentMethod } from './paymentMethod';


export interface ApplicablePaymentMethods { 
    /**
     * The array of applicable payment methods for this basket.
     */
    paymentMethods: PaymentMethod;
    /**
     * The checkout id related to this basket.
     */
    checkoutId?: string;
}
