/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AuthorizedPaymentInstrument { 
    /**
     * Payment authentication results we have from payment provider
     */
    authResult: string;
    /**
     * Merchant reference value received from payment provider
     */
    merchantReference: string;
    /**
     * Merchant signature value received from payment provider on previous step
     */
    merchantSig: string;
    /**
     * The payment method id. For example \"paypal\"
     */
    paymentMethod: string;
    /**
     * Payment reference reference value received from payment provider
     */
    pspReference: string;
    /**
     * The locale of the ecom shop.
     */
    shopperLocale: string;
    /**
     * Skip code value received from payment provider
     */
    skinCode: string;
}
