/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BillingAddress } from './billingAddress';
import { Customer } from './customer';
import { ShippingAddress } from './shippingAddress';


export interface BasketModification { 
    /**
     * The billing address
     */
    billingAddress?: BillingAddress;
    /**
     * The shipping address
     */
    shippingAddress?: ShippingAddress;
    /**
     * Customer related information
     */
    customer?: Customer;
    /**
     * The shipping methods to be set for this basket
     */
    methodList?: Array<any>;
    /**
     * A flag to enable or not newsletter subscription for this user
     */
    newsletterSubscription?: boolean;
    /**
     * Set pickup point for e.g. CnC
     */
    pickupPoint?: any;
    /**
     * string used to deliver information about ongoing AB tests.
     */
    segmentationId?: string;
}
