/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StateCode } from './stateCode';


/**
 * Required Fields are market specific and defined via configurations
 */
export interface BillingAddress { 
    /**
     * The unique address id
     */
    id?: string;
    /**
     * The address line 1 information
     */
    address1?: string;
    /**
     * The address line 2 information
     */
    address2?: string;
    /**
     * City information
     */
    city?: string;
    /**
     * Country information
     */
    country?: string;
    /**
     * Zipcode information
     */
    zipcode?: string;
    /**
     * The two digit code for a state
     */
    stateCode?: StateCode;
    /**
     * First name information
     */
    firstName?: string;
    /**
     * Last name information
     */
    lastName?: string;
    /**
     * County province information
     */
    countyProvince?: string;
    /**
     * Company name information
     */
    companyName?: string;
    /**
     * Apartment number information
     */
    apartmentNumber?: string;
    /**
     * House number information
     */
    houseNumber?: string;
    /**
     * Suburb information
     */
    suburb?: string;
    /**
     * Island information
     */
    island?: string;
}
