/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CnCStoreModification { 
    /**
     * Click and Collect store id to set the store or null to remove it
     */
    cncStoreId?: string;
    /**
     * Longitude
     */
    lon?: number;
    /**
     * Latitude
     */
    lat?: number;
}
