/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomerEmail } from './customerEmail';


export interface Customer { 
    /**
     * Customer's unique id of SFCC
     */
    customerId?: string;
    /**
     * Customer's name
     */
    name?: string;
    /**
     * It represents customer email address
     */
    email?: CustomerEmail;
    /**
     * Encrypted version of customer email. Used for analytics purposes
     */
    encryptedEmail?: string;
    /**
     * Should the customer receive SMS notifications. Only enabled for CnC delivery.
     */
    receiveSmsUpdates?: boolean;
    /**
     * Defines if this customer is logged in or not.
     */
    isLoggedIn?: boolean;
}
