/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Price } from './price';


export interface Discount { 
    /**
     * The unique id of promotion
     */
    id: string;
    /**
     * The name of promotion
     */
    name: string;
    price: Price;
    /**
     * Callout message of promotion. It can be an HTML content
     */
    calloutMessage?: string;
    /**
     * it's used to link coupon item id in couponList attribute
     */
    couponItemId?: string;
}
