/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * A machine-readable error details that can be used for displaying error on API consumer side
 */
export interface ErrorResponseDetails { 
    /**
     * Currently available stock for item that user is trying to order
     */
    availableQuantity?: number;
}
