/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface GiftCertificate { 
    /**
     * The gift card number
     */
    cardNumber: string;
    /**
     * The pin number of the gift card
     */
    pinNumber: string;
    /**
     * The amount authorized by this gift card
     */
    amount?: number;
}
