/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Price } from './price';


export interface LineItemContainerPricing { 
    /**
     * The total of the basket, this includes discounts, line items and shipping. If the taxation policy is GROSS, it also includes tax. If the taxation policy is NET, it does not include tax
     */
    total: Price;
    /**
     * The total of the basket before order level discounts, this includes line item discounts, line items and shipping. If the taxation policy is GROSS, it also includes tax. If the taxation policy is NET, it does not include tax
     */
    baseTotal: Price;
    /**
     * The total tax amount. This includes shipping and line item tax as well as tax reductions through all discounts
     */
    totalTax: Price;
    /**
     * The total of the line items this excludes shipping costs and order level discounts, but includes line item discounts
     */
    productTotal: Price;
    /**
     * The total of line items, excluding shipping costs, order level discounts and line item discounts
     */
    productTotalBeforeDiscounts: Price;
    /**
     * The total of line items, excluding shipping costs and order level discounts
     */
    productTotalBeforeOrderDiscounts: Price;
    /**
     * The total shipping costs including shipping discounts
     */
    shippingTotal: Price;
    /**
     * The total of the shipping costs before discounts
     */
    shippingBaseTotal: Price;
}
