/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MessageDetail } from './messageDetail';


export interface Message { 
    /**
     * It shows the type of message; info, warn, error or success
     */
    messageType?: Message.MessageTypeEnum;
    /**
     * It shows type of error.
     */
    type?: string;
    details?: MessageDetail;
}
export namespace Message {
    export type MessageTypeEnum = 'INFO' | 'WARN' | 'ERROR' | 'SUCCESS';
    export const MessageTypeEnum = {
        INFO: 'INFO' as MessageTypeEnum,
        WARN: 'WARN' as MessageTypeEnum,
        ERROR: 'ERROR' as MessageTypeEnum,
        SUCCESS: 'SUCCESS' as MessageTypeEnum
    }
}
