/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductId } from './productId';


export interface MessageDetail { 
    /**
     * The unique SKU
     */
    productId?: ProductId;
    /**
     * Unique shipment id
     */
    shipmentId?: string;
    articleNumber?: string;
    maximumQuantity?: number;
    requestedQuantity?: number;
    availableQuantity?: number;
    outOfStockLetters?: Array<string>;
    outOfStockNumbers?: Array<string>;
    badgeMissing?: boolean;
}
