/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type OrderStatus = 'created' | 'new' | 'open' | 'completed' | 'cancelled' | 'replaced' | 'failed';

export const OrderStatus = {
    Created: 'created' as OrderStatus,
    New: 'new' as OrderStatus,
    Open: 'open' as OrderStatus,
    Completed: 'completed' as OrderStatus,
    Cancelled: 'cancelled' as OrderStatus,
    Replaced: 'replaced' as OrderStatus,
    Failed: 'failed' as OrderStatus
}
