/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthorizedPaymentInstrument } from './authorizedPaymentInstrument';
import { BasketId } from './basketId';
import { PaymentInstrument } from './paymentInstrument';


export interface OrderRequest { 
    /**
     * The id of the basket associated with this order
     */
    basketId: BasketId;
    /**
     * The payment instrument used to pay for this basket
     */
    paymentInstrument?: PaymentInstrument;
    /**
     * The authorized payment instrument used for submitting order with Hosted Payment Page method
     */
    authorizedPaymentInstrument?: AuthorizedPaymentInstrument;
    /**
     * The encrypted instrument information
     */
    encryptedInstrument?: string;
    /**
     * The payment provider fingerprint
     */
    fingerprint?: string;
}
