/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PaymentCardSpecification } from './paymentCardSpecification';


export interface PaymentMethod { 
    /**
     * The id of the payment method or card.
     */
    id: string;
    /**
     * The localized name of the payment method or card.
     */
    name?: string;
    /**
     * The localized description of the payment method or card.
     */
    description?: string;
    /**
     * The sorted array of payment cards (included only when the system payment method is CREDIT_CARD).
     */
    cards?: PaymentCardSpecification;
}
