/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Price } from './price';


export interface PaymentInstrument { 
    /**
     * The unique payment instrument id
     */
    id?: string;
    /**
     * The payment transaction amount
     */
    amount?: Price;
    /**
     * Card type. example; VISA
     */
    cardType?: string;
    /**
     * It represents expiration month of card
     */
    expirationMonth?: number;
    /**
     * It represents expiration year of card
     */
    expirationYear?: number;
    /**
     * The name written on payment card
     */
    holder?: string;
    /**
     * It shows the last 4 digit of card
     */
    lastFour?: string;
    /**
     * The payment method id. example; CREDIT_CARD
     */
    paymentMethodId: string;
    /**
     * The total current balance on the gift card
     */
    balance?: number;
    /**
     * The masked gift card number
     */
    maskedGiftCardNumber?: string;
}
