/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Store } from './store';


/**
 * Pickup point details
 */
export interface PickupPoint { 
    /**
     * Pickup point store if using CnC
     */
    cncStore?: Store;
    /**
     * A pickup point (ie. Paketstation, DHL Boxes, etc) if using PUDO Delivery
     */
    pudoStore?: Store;
}
