/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MasterProductId } from './masterProductId';
import { ProductId } from './productId';
import { Recipe } from './recipe';


export interface ProductToAdd { 
    /**
     * The unique SKU
     */
    productId: ProductId;
    /**
     * The amount of product to be added to cart. By default is 1
     */
    quantity?: number;
    /**
     * The recipe specification for personalized products
     */
    recipe?: Recipe;
    /**
     * The unique receipe id sent from miconfigurator. It is used to validate personalization recipe
     */
    recipeId?: string;
    /**
     * The unique receipe id sent from miconfigurator. It is used to validate customization recipe
     */
    customizationRecipeId?: string;
    /**
     * TheUnique master product id.
     */
    masterProductId?: MasterProductId;
    /**
     * The country specific size value.
     */
    displaySize?: string;
    /**
     * google captcha response
     */
    captchaResponse?: string;
    /**
     * Segmentation string used to define the customer group for the basket.
     */
    segmentationId?: string;
}
