/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PUDOModification { 
    /**
     * The id for the PUDO box that the customer will pickup his package
     */
    pudoId?: string;
    /**
     * The customer postnumber id that he will use to pickup his package
     */
    postNumber?: string;
}
