/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PersonalizationOptions } from './personalizationOptions';


export interface Recipe { 
    /**
     * The article number that this recipe is based on
     */
    articleNumber: string;
    /**
     * The quantity of products that will use this recipe
     */
    quantity: number;
    /**
     * The recipe options
     */
    selectedOptions: PersonalizationOptions;
    /**
     * The sku of the item
     */
    sku?: string;
    /**
     * The size based on country-specific sizes
     */
    countrySize?: string;
    /**
     * The unique technical size (same across all countries)
     */
    technicalSize?: string;
}
