/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface RefundData { 
    /**
     * Return Order Number provided by OMS to link payout request to refund case
     */
    returnOrderNumber: string;
    /**
     * Amount of money in local currency to be refunded (decimal value is used). This value will be validated before any money is processed
     */
    refundAmount: number;
    /**
     * 3-character Adyen currency code for the amount refunded. This value will be validated before any money is processed
     */
    currency: string;
    /**
     * Email of the consumer who initiated refund request
     */
    shopperEmail: string;
    /**
     * The first name of the customer who initiated the refund request
     */
    shopperFirstName: string;
    /**
     * The last name of the customer who initiated the refund request
     */
    shopperLastName: string;
    /**
     * ISO 2-character country code
     */
    shopperNationality: string;
    /**
     * Birthdate of the consumer, in 'ISO-8601' format YYYY-MM-DD
     */
    shopperDateOfBirth: string;
    /**
     * eUCI of the consumer, provided by backend system
     */
    consumerEuci: string;
    /**
     * Full name of the bank account holder (name and surname)
     */
    accountHolderName: string;
    /**
     * Name of the bank institute
     */
    bankName: string;
    /**
     * International Bank Account Number in Europe
     */
    iban: string;
}
