/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ShippingMethodType = 'inline' | 'miadidas' | 'preorder' | 'backorder' | 'yourreebok';

export const ShippingMethodType = {
    Inline: 'inline' as ShippingMethodType,
    Miadidas: 'miadidas' as ShippingMethodType,
    Preorder: 'preorder' as ShippingMethodType,
    Backorder: 'backorder' as ShippingMethodType,
    Yourreebok: 'yourreebok' as ShippingMethodType
}
