/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GroupCodesType } from './groupCodesType';
import { Price } from './price';
import { ShippingMethodType } from './shippingMethodType';
import { TimeInterval } from './timeInterval';


export interface ShippingMethod { 
    /**
     * Unique identification of shipping method.
     */
    id: string;
    /**
     * Determines the type of shipping method.
     */
    type?: Array<ShippingMethodType>;
    /**
     * Name of shipping method.
     */
    name?: string;
    /**
     * Description of shipping method.
     */
    description?: string;
    /**
     * The name of service which delivers order
     */
    carrierName?: string;
    /**
     * Carier code
     */
    carrierCode?: string;
    /**
     * Carier service code
     */
    carrierServiceCode?: string;
    /**
     * Carier service name
     */
    carrierServiceName?: string;
    /**
     * Carier group codes
     */
    groupCodes?: Array<GroupCodesType>;
    /**
     * The collection time interval of the shipping method
     */
    collection?: TimeInterval;
    /**
     * The delivery time interval of the shipping method
     */
    delivery?: TimeInterval;
    /**
     * The cost of shipping method.
     */
    price?: Price;
    /**
     * It shows whether shipping method is default
     */
    isDefault?: boolean;
    /**
     * It represents the identifiaction what shipping method belongs to
     */
    shipmentId?: string;
    /**
     * Message informing of the potential delay
     */
    delayMessage?: string;
}
