/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModelDate } from './modelDate';
import { ProductLineItem } from './productLineItem';


export interface Shipment { 
    /**
     * The unique id of shipment
     */
    shipmentId: string;
    /**
     * the date of shipping starts for backorder and preorder products.
     */
    shippingOnDate?: ModelDate;
    /**
     * Identify shipment type; inline, miadidas, preorder, backorderm yourreebok
     */
    shipmentType?: Shipment.ShipmentTypeEnum;
    productLineItemList: Array<ProductLineItem>;
    shippingLineItem: any;
}
export namespace Shipment {
    export type ShipmentTypeEnum = 'inline' | 'miadidas' | 'preorder' | 'backorder' | 'yourreebok';
    export const ShipmentTypeEnum = {
        Inline: 'inline' as ShipmentTypeEnum,
        Miadidas: 'miadidas' as ShipmentTypeEnum,
        Preorder: 'preorder' as ShipmentTypeEnum,
        Backorder: 'backorder' as ShipmentTypeEnum,
        Yourreebok: 'yourreebok' as ShipmentTypeEnum
    }
}
