/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WorkingTime } from './workingTime';


export interface StoreOpeningHours { 
    monday?: WorkingTime;
    tuesday?: WorkingTime;
    wednesday?: WorkingTime;
    thursday?: WorkingTime;
    friday?: WorkingTime;
    saturday?: WorkingTime;
    sunday?: WorkingTime;
}
