/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StoreDeliveryWindow } from './storeDeliveryWindow';
import { StoreOpeningHours } from './storeOpeningHours';


/**
 * A store from where items can be picked from along with address and open hours
 */
export interface Store { 
    /**
     * Unique store ID
     */
    id?: string;
    /**
     * Store name
     */
    name?: string;
    /**
     * Street
     */
    street?: string;
    /**
     * City
     */
    city?: string;
    /**
     * Postal code
     */
    postalCode?: string;
    telephoneNumber?: string;
    state?: string;
    /**
     * Street
     */
    country?: string;
    /**
     * Distance to search location in km
     */
    distance?: number;
    latitude?: number;
    longitude?: number;
    openingHours?: StoreOpeningHours;
    /**
     * Number of days required to deliver products in store. When 0, products are in store and can be picked up today.
     */
    daysToWaitForDelivery?: number;
    deliveryWindow?: StoreDeliveryWindow;
}
