/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * An estimation range for the days days required to deliver products in store. When numbers are the same, there's no uncertainty about the pickup time. When 0, products are in store and can be picked up today.
 */
export interface StoreDeliveryWindow { 
    from?: number;
    to?: number;
}
