/**
 * eCom Checkout API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TaxBreakdown { 
    /**
     * The name of the field to be displayed on each tax breakdown.
     */
    name?: string;
    /**
     * The value of the field to bed displayed on each tax breakdown
     */
    value?: string;
}
